[metadata]
name = byted_pysisyphus
version = attr: byted_pysisyphus.__version__
description = Bytedance mirror of pysisyphus, a Python suite for exploring potential energy surfaces.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/bytedance/byted-pysisyphus
maintainer = Henry Wang
maintainer_email = henry.wang1@bytedance.com
license = GNU General Public License v3 (GPLv3)
platform = unix
classifiers =
    License :: OSI Approved :: GNU General Public License v3 (GPLv3)

[options]
packages = find:
include_package_data = True
python_requires = >=3.8
install_requires =
    autograd
    dask
    distributed
    h5py
    fabric
    jinja2
    joblib
    matplotlib
    numpy
    natsort
    psutil
    pyyaml
    rmsd
    scipy
    sympy
    scikit-learn

[options.extras_require]
test = pyscf; pytest; pytest-cov; ase; qcengine
doc = sphinx; sphinx-rtd-theme ; sphinx_autodoc_typehints

[options.entry_points]
console_scripts =
    byted_pysis = byted_pysisyphus.run:run
    byted_pysisplot = byted_pysisyphus.plot:run
    byted_pysistrj = byted_pysisyphus.trj:run
    byted_pysisdia = byted_pysisyphus.drivers.diabatization:run
    byted_pysisfilter = byted_pysisyphus.filtertrj:run
    byted_pysispack = byted_pysisyphus.pack:run
    byted_pysisthermo = byted_pysisyphus.drivers.thermo:run_thermo
    byted_pysismerge = byted_pysisyphus.drivers.merge:run_merge
    byted_pysisreplace = byted_pysisyphus.drivers.replace:run
    byted_pysisrc = byted_pysisyphus.config:run_detect_paths
    byted_pysisconfig = byted_pysisyphus.config:create_default_config
    byted_pysiswigner = byted_pysisyphus.dynamics.wigner:run
